# Generated by Django 4.1.1 on 2022-09-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_color_image_remove_size_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_codigo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
