# Generated by Django 4.1.1 on 2022-09-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_color_color_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='cat_imgs/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='image',
            field=models.ImageField(null=True, upload_to='marca_imgs/'),
        ),
    ]
